### PR TITLE
[v1.9.x] stop closing opened libs

### LINKED ISSUE #20411: 1.7.0.post2: consistent segfault in ~LibraryInitializer() with loaded extensions on OSX Mojave
## Description
I've recently started using the C++ custom operator framework.  It's great and I like it a lot, but for some reason mxnet always segfaults on program exit when I've loaded a custom operator.  This happens with all custom operators, even the tutorial operator gemm_lib.

This is on OSX Mojave, g++ version "Apple LLVM version 10.0.1 (clang-1001.0.46.4)".  mxnet comes from pip, version 1.7.0.post2.

### Error Message
Since it's a segfault there's not a backtrace as such, but here's the tail of a representative lldb session:

* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x0000000118105283 libmxnet.dylib`mxnet::LibraryInitializer::~LibraryInitializer() + 67
libmxnet.dylib`mxnet::LibraryInitializer::~LibraryInitializer:
->  0x118105283 <+67>: movq   (%rcx), %rcx
    0x118105286 <+70>: testq  %rcx, %rcx
    0x118105289 <+73>: jne    0x118105280               ; <+64>
    0x11810528b <+75>: jmp    0x1181052b0               ; <+112>
Target 0: (python) stopped.
(lldb) thread backtrace
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x0000000118105283 libmxnet.dylib`mxnet::LibraryInitializer::~LibraryInitializer() + 67
    frame #1: 0x00007fff786ef3cf libsystem_c.dylib`__cxa_finalize_ranges + 319
    frame #2: 0x00007fff786ef6b3 libsystem_c.dylib`exit + 55
    frame #3: 0x00007fff786493dc libdyld.dylib`start + 8
    frame #4: 0x00007fff786493d5 libdyld.dylib`start + 1

## To Reproduce
`make gemm_lib && python test_gemm.py` from [the custom op tutorial](https://github.com/apache/incubator-mxnet/blob/master/example/extensions/lib_custom_op/README.md) shows the error for me.

## Things That Didn't Work
Building my own mxnet 1.7.0 from source didn't help.  The content of the custom op doesn't seem to matter either.

## Environment
<details>
<summary>Environment Information</summary>

----------Python Info----------
Version      : 3.6.5
Compiler     : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
Build        : ('default', 'Apr 26 2018 08:42:37')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 21.1.3
Directory    : /Users/davseile/miniconda3/lib/python3.6/site-packages/pip
----------MXNet Info-----------
/Users/davseile/miniconda3/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Version      : 1.7.0
Directory    : /Users/davseile/miniconda3/lib/python3.6/site-packages/mxnet
Commit Hash   : 64f737cdd59fe88d2c5b479f25d011c5156b6a8a
Library      : ['/Users/davseile/miniconda3/lib/python3.6/site-packages/mxnet/libmxnet.dylib']
Build features:
✖ CUDA
✖ CUDNN
✖ NCCL
✖ CUDA_RTC
✖ TENSORRT
✔ CPU_SSE
✔ CPU_SSE2
✔ CPU_SSE3
✔ CPU_SSE4_1
✖ CPU_SSE4_2
✖ CPU_SSE4A
✖ CPU_AVX
✖ CPU_AVX2
✖ OPENMP
✖ SSE
✖ F16C
✖ JEMALLOC
✖ BLAS_OPEN
✖ BLAS_ATLAS
✖ BLAS_MKL
✔ BLAS_APPLE
✔ LAPACK
✔ MKLDNN
✔ OPENCV
✖ CAFFE
✖ PROFILER
✖ DIST_KVSTORE
✖ CXX14
✖ INT64_TENSOR_SIZE
✔ SIGNAL_HANDLER
✖ DEBUG
✖ TVM_OP
----------System Info----------
Platform     : Darwin-18.7.0-x86_64-i386-64bit
system       : Darwin
node         : 00e04c166570
release      : 18.7.0
version      : Darwin Kernel Version 18.7.0: Mon May  3 20:41:19 PDT 2021; root:xnu-4903.278.68~1/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.brand_string: Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.leaf7_features: RDWRFSGS TSC_THREAD_OFFSET SGX BMI1 HLE AVX2 SMEP BMI2 ERMS INVPCID RTM FPU_CSDS MPX RDSEED ADX SMAP CLFSOPT IPT MDCLEAR TSXFA IBRS STIBP L1DF SSBD'
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI'
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0430 sec, LOAD: 0.7044 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0961 sec, LOAD: 0.5755 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>, DNS finished in 0.08476710319519043 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0732 sec, LOAD: 0.3876 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0459 sec, LOAD: 1.0816 sec.
Error open Conda: https://repo.continuum.io/pkgs/free/, HTTP Error 403: Forbidden, DNS finished in 0.06121397018432617 sec.
----------Environment----------

</details>

### PR DESCRIPTION
**Pull request by samskalicky**
## Description ##
stop closing opened libs. fixes #20411 using portions already merged into master/2.0 in #19016. 

According to [[1]](https://pubs.opengroup.org/onlinepubs/009695399/functions/dlclose.html) 

> The dlclose() function shall inform the system that the object referenced by a handle returned from a previous dlopen() invocation is no longer needed by the application.

> The use of dlclose() reflects a statement of intent on the part of the process, but does not create any requirement upon the implementation, such as removal of the code or symbols referenced by handle.

So calling `dlclose` is just a suggestion to the OS that it could close the library. But the OS may not do anything (ie. and wait until the process exits to clean up any opened handles). Im thinking we might as well just let it be cleaned up anyway rather than calling `dlclose` at all. 

As suggested in [[2]](https://stackoverflow.com/a/26131259)

> If you only ever open one library, use it throughout your program, then calling dlclose just before you exit is probably not essential, but if you open a lot of libraries (e.g. using some sort of plugin in a long-running program that can/will use many different plugins, the program may run out of virtual address space if you don't call dlclose.

> (All shared libraries are closed on exit anyway, so leaving it open at exit should not be an issue)

So if a user was loading/unloading a bunch of libraries at runtime they might want to close some they dont need anymore. 

However, since MXNet registers components from the library (ie. operators, partitioners, graph passes, etc) and has NO capability to unregister them the references to the loaded library will live at least as long as MXNet (ie. libmxnet.so) does. MXNet already has quite a few components (or its dependencies like TVM/NNVM) that live forever and require the OS to clean them up when the process exits. So its not possible to close libmxnet.so and assume everything is cleaned up. We might as well do the same thing for custom libraries. 

This PR removes the code to close opened libraries in the destructor of the `LibraryInitializer` class with the caveat that MXNet will still have pointers to that library, so closing would not be recommended until process exit anyway.

### CODE REVIEW

**Comment by samskalicky** [comment]
Manual build on Mac runs the gemm_lib example in extensions without segfault

File: include/mxnet/c_api.h [hunk 1]
```diff
@@ -233,10 +233,11 @@ MXNET_DLL const char *MXGetLastError();
 /*!
  * \brief Load library dynamically
  * \param path to the library .so file
- * \param 0 for quiet, 1 for verbose
+ * \param verbose 0 for quiet, 1 for verbose
+ * \param lib handle to opened library
  * \return 0 when success, -1 when failure happens.
  */
-MXNET_DLL int MXLoadLib(const char *path, unsigned verbose);
+MXNET_DLL int MXLoadLib(const char *path, unsigned verbose, void** lib);
```
Comment (szha) [inline include/mxnet/c_api.h:240]: This is a C API change. Is it required for the fix?

Comment (samskalicky) [reply include/mxnet/c_api.h:240]: Thanks for the review @szha! No this change isnt required, but without it we cannot return a handle to the opened library. Its not required per-se since opening the same library using ctypes or some other API will return the same handle anyway (with linux doing the mapping). So we can remove this change if that is important, either way is fine to me.

**Comment by mseth10** [comment]
Thanks for the PR. The destructor change looks good.

What's the benefit of returning handle to opened library, if it's not recommended that users close them? Is there any other use case?

File: include/mxnet/c_api.h (hunk 1 above)
Comment (szha) [reply include/mxnet/c_api.h:240]: C API is part of the API to maintain semantic versioning for. Let's not include the API change then.

**Comment by samskalicky** [comment]
Thanks @szha @mseth10 ive made the changes to not remove the handle. Now this PR is effectively just not closing opened libraries on exit (and some misc comment updates)

**Review by szha — APPROVED** [review]

**Review by mseth10 — APPROVED** [review]
LGTM
