### PR TITLE
[Numpy] Misc fix

### LINKED ISSUE #14342: Ensure all usage of `ndim` to be 0-d tensor compatible
EDIT: See also #14323.

After #14315, we should check all the occurrence of `ndim` to ensure they are used correctly in the semantics of 0-d tensor.

@reminisce @szha @eric-haibin-lin @zheng-da @yzhliu

# List of occurrence
## src/c_api
* [x] src/c_api/c_api.cc
* [x] src/c_api/c_api_common.h
* [x] src/c_api/c_api_symbolic.cc
* [x] src/c_api/c_predict_api.cc

## src/common
* [x] src/common/serialization.h
* [x] src/common/static_array.h
* [x] src/common/utils.h

## src/executor
* [x] src/executor/infer_graph_attr_pass.cc

## src/imperative
* [x] src/imperative/cached_op.cc
* [x] src/imperative/imperative_utils.h

## src/io
* [x] src/io/image_aug_default.cc
* [x] src/io/image_det_aug_default.cc
* [x] src/io/image_io.cc
* [x] src/io/image_iter_common.h
* [x] src/io/iter_batchloader.h
* [x] src/io/iter_image_det_recordio.cc
* [x] src/io/iter_image_recordio_2.cc
* [x] src/io/iter_libsvm.cc
* [x] src/io/iter_sparse_batchloader.h

## src/kvstore
* [x] src/kvstore/gradient_compression.cc
* [x] src/kvstore/kvstore_dist.h
* [x] src/kvstore/kvstore_dist_server.h

## src/ndarray
* [x] src/ndarray/ndarray.cc
* [x] src/ndarray/ndarray_function.cc
* [x] src/ndarray/ndarray_function.cu
* [x] src/ndarray/ndarray_function.h

## src/nnvm
Nothing here.

## include
* [x] include/mxnet/ndarray.h
* [x] include/mxnet/operator.h
* [x] include/mxnet/operator_util.h
* [x] include/mxnet/resource.h
* [x] include/mxnet/tensor_blob.h
* [x] include/mxnet/tuple.h

### PR DESCRIPTION
**Pull request by junrushao1994**
Should fix #14342

@reminisce

### CODE REVIEW

File: src/ndarray/ndarray.cc [hunk 1]
```diff
@@ -1663,7 +1663,7 @@ bool NDArray::LegacyLoad(dmlc::Stream *strm, const uint32_t magic) {
   // load shape
   mxnet::TShape shape;
   if (!LegacyTShapeLoad(strm, &shape, magic)) return false;
-  if (shape.ndim() == 0) {
+  if (mxnet::op::shape_is_none(shape)) {
```
Comment (junrushao1994) [inline src/ndarray/ndarray.cc]: @reminisce Not sure if it is the correct fix. It is in save/load.

**Comment by piyushghai** [comment]
Thanks for your contributions @junrushao1994. 
Can you look into the CI failures ? 

@mxnet-label-bot Add [Numpy, pr-awaiting-review]

File: src/ndarray/ndarray.cc (hunk 1 above)
Comment (reminisce) [reply src/ndarray/ndarray.cc]: This should be fine.

File: src/ndarray/ndarray.cc [hunk 2]
```diff
@@ -1711,7 +1711,7 @@ bool NDArray::Load(dmlc::Stream *strm) {
   // load shape
   mxnet::TShape shape;
   if (!shape.Load(strm)) return false;
-  if (shape.ndim() == 0) {
+  if (mxnet::op::shape_is_none(shape)) {
```
Comment (reminisce) [inline src/ndarray/ndarray.cc]: We may need to check whether the current mode is numpy compatible. If not, we need to conver `shape` to numpy shape first and then call `shape_is_none/shape_is_known`.

File: src/kvstore/gradient_compression.cc [hunk 3]
```diff
@@ -100,9 +100,9 @@ int64_t GradientCompression::GetCompressedSize(const int64_t original_size) {
 
 void GradientCompression::Quantize(const mxnet::NDArray &from, mxnet::NDArray *to,
                   mxnet::NDArray *residual, const int priority) {
-  CHECK(from.shape().ndim() != 0) << "source operand has zero dimension shape";
-  CHECK(to->shape().ndim() != 0) << "destination operand has zero dimension shape";
-  CHECK(residual->shape().ndim() != 0) << "residual operand has zero dimension shape";
+  CHECK(!mxnet::op::shape_is_none(from.shape())) << "source operand has undefined shape";
```
Comment (reminisce) [inline src/kvstore/gradient_compression.cc]: One suggestion here: we'd better use `shape_is_known` going forward, instead of `shape_is_none`, because the latter's naming has the flavor of negative boolean which is usually not recommended in practice.

Comment (junrushao1994) [reply src/kvstore/gradient_compression.cc]: Got it. Thanks!

**Comment by junrushao1994** [comment]
Updated accordingly! Could you review again? Thanks @reminisce

File: src/ndarray/ndarray.cc [hunk 4]
```diff
@@ -1711,7 +1711,10 @@ bool NDArray::Load(dmlc::Stream *strm) {
   // load shape
   mxnet::TShape shape;
   if (!shape.Load(strm)) return false;
-  if (shape.ndim() == 0) {
+  if (Imperative::Get()->is_np_comp()) {
```
Comment (reminisce) [inline src/ndarray/ndarray.cc]: Actually, it should be `if (!Imperative::Get()->is_np_comp()) {`.

Comment (junrushao1994) [reply src/ndarray/ndarray.cc]: My bad...fixed!

**Comment by junrushao1994** [comment]
I tried nosetests a litte bit, and everything seems to be fine
