### PR TITLE
Fix relative difference scala

### LINKED ISSUE #14402: Scala arange Flaky test
Currently, I received several reports from contributors about the failed test they got from CI:
```
[31m- arange *** FAILED ***[0m
[31m  NaN was not less than or equal to 1.0E-4 (NDArraySuite.scala:353)[0m
```
Some problems appeared in the CI:

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14365/7/pipeline/281

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-14359/7/pipeline

Thanks @haojin2 @yuxihu reporting these issues

### PR DESCRIPTION
**Pull request by kiendang**
## Description ##
Fix #14402 where division by zero occurs in relative difference calculation, making `arange` tests fail.
Solution: if `diff` is near 0f, i.e < `Float.MinPositiveValue` just return it instead of dividing by `norm`.

Also ~~increase number of test cases to 10000~~ add test cases where `arange` produces NDArray of [0.0f] to catch this. Test is not flaky anymore.
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

#14413 @lanking520 @perdasilva

### CODE REVIEW

File: scala-package/core/src/test/scala/org/apache/mxnet/NDArraySuite.scala [hunk 1]
```diff
@@ -335,7 +335,7 @@ class NDArraySuite extends FunSuite with BeforeAndAfterAll with Matchers {
   }
 
   test("arange") {
-    for (i <- 0 until 5) {
+    for (i <- 0 until 10000) {
```
Comment (marcoabreu) [inline scala-package/core/src/test/scala/org/apache/mxnet/NDArraySuite.scala]: Instead of increasing the number of iterations, could you maybe add a test case that specifically hits the behaviour you're trying to circumvent here?

**Comment by marcoabreu** [comment]
Thanks a lot for your contribution - nice catch!

File: scala-package/core/src/test/scala/org/apache/mxnet/NDArraySuite.scala (hunk 1 above)
Comment (kiendang) [reply scala-package/core/src/test/scala/org/apache/mxnet/NDArraySuite.scala]: Sure. That's definitely a better solution.

Comment (marcoabreu) [reply scala-package/core/src/test/scala/org/apache/mxnet/NDArraySuite.scala]: Awesome, thanks!

Comment (marcoabreu) [reply scala-package/core/src/test/scala/org/apache/mxnet/NDArraySuite.scala]: @lanking520 @nswamy could you give me a hand here and review the scala code?

**Comment by kiendang** [comment]
Oops
