### PR TITLE
[BUGFIX] Fix accuracy issue due to reuse of primitives for MKLDNN-AArch64. Fixes #20265.

### LINKED ISSUE #20265: [v1.x] [MKLDNN] 2 Conv Tests Failed with MKLDNN + ACL
I was trying to build MXNet 1.x with MKLDNN with ACL (Arm Compute Library) integration on an Arm instance. I used this [cmake config file](https://github.com/apache/incubator-mxnet/blob/v1.x/config/distribution/linux_aarch64_cpu.cmake) to integrate MKLDNN with ACL. The build was very performant and would surely benefit MXNet users hugely. I got a 3-4X boost with (16/64, 3, 512, 512) on Resnet compared to MKLDNN with no integration. However two operator unit test failed on this build:
```
test_operator.test_convolution_grouping 
test_operator.test_convolution_independent_gradients
```
I tried multiple mkldnn versions (v1.x now points to mkldnn release 2.0 beta 10, I also tried release 2.1 and 2.2) and ACl versions (20.08 and 21.2, 20.08 is Aug 2020 and 21.2 is the latest) and the failures persisted.

This got me suspect that there is some integration issue with MXNet-MKLDNN (more possible) or MKLDNN-ACL. Would someone from the Intel team help share some insights on this?

Would you help triage?@szha @leezu 

CC @josephevans @mseth10 @waytrue17 @sandeep-krishnamurthy

### PR DESCRIPTION
**Pull request by cfRod**
## Description ##

This fix is a workaround for the accuracy issue in the grouped convolution unit test observed when MXNet is built with Compute Library for Arm Architecture (ACL).
Fixes https://github.com/apache/incubator-mxnet/issues/20265
This change includes:
* Updating MXNet's existing AddSign function to generate unique hashes for MKLDNN-ACL backend.
* Adds a new AddSign overloaded function to generate hashes based on uint64_t type.
* Adding DNNL_AARCH64_USE_ACL definition to CMakeLists.txt
* Adding Crefeda Rodrigues to the contributors list

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### Changes ###
- [X] Updating MXNet's existing AddSign function to generate unique hashes for MKLDNN-ACL backend.
- [X] Adds a new AddSign overloaded function to generate hashes based on uint64_t type.
- [X] Adding DNNL_AARCH64_USE_ACL definition to CMakeLists.txt
- [X] Adding Crefeda Rodrigues to the contributors list

## Comments ##
- This change is a workaround to resolve the accuracy issue seen test_operator.test_convolution_grouping until future releases of Compute library are compatible with reuse of MKLDNN/oneDNN primitives at the framework-level.

### CODE REVIEW

**Comment by cfRod** [comment]
Hi,

I will be away until 20th August. Any issues with this PR I will address when I am back. Thanks.

File: src/operator/operator_common.h [hunk 1]
```diff
@@ -620,6 +620,10 @@ class OpSignature {
       hash = hash * 2 + arr.dtype();
       eles.push_back(arr.dtype());
       AddSign(arr.shape());
+#if DNNL_AARCH64_USE_ACL == 1
+      auto ival = reinterpret_cast<const uint64_t>(arr.storage_handle().dptr);
+      AddSign(ival);
+#endif
```
Comment (mseth10) [inline src/operator/operator_common.h:626]: Why is this only needed when `arr.IsMKLDNNData()` is `False`?

Comment (cfRod) [reply src/operator/operator_common.h:626]: I checked that this function (arr.IsMKLDNNData()) is called for mkldnn blocked format types https://github.com/apache/incubator-mxnet/blob/7e835a592da902066f2ccb0d74a78adc8e77fdb7/include/mxnet/ndarray.h#L714 and here https://github.com/apache/incubator-mxnet/blob/7e835a592da902066f2ccb0d74a78adc8e77fdb7/src/operator/nn/mkldnn/mkldnn_base.cc#L309 which is not used for ACL builds.

Comment (cfRod) [reply src/operator/operator_common.h:626]: @szha, @mseth10, is there anything that needs resolving here?

Comment (szha) [reply src/operator/operator_common.h:626]: I'm also trying to understand why the hash on pointer address is only needed when building ARM64 with oneDNN.

Comment (cfRod) [reply src/operator/operator_common.h:626]: Hi @szha, 
As mentioned we have an issue here #2026, where re-using  primitives causes accuracy failures for an Arm build of MxNET (which is built with Compute Library for Arm). This is a fix we have added to other frameworks like TensorFlow too, issue here https://github.com/tensorflow/tensorflow/issues/47415 and PR raised here https://github.com/tensorflow/tensorflow/commit/06dd30ef987b5511351e979568d4ad06ccdc2844. Please also refer to the discussion with oneDNN team https://github.com/oneapi-src/oneDNN/issues/1113.
As stated previously, this is a workaround we have had to add at the framework level until this issue can be resolved in future releases of Compute Library.

Comment (szha) [reply src/operator/operator_common.h:626]: OK, thanks for the clarification on the plan to fix. I'm OK with the change and it would be great if you could add a comment in the code on the context and the plan to fix.

Comment (cfRod) [reply src/operator/operator_common.h:628]: Done

**Comment by cfRod** [comment]
Hi,
 I see that the linting test fails. What linting tool should I use to test this locally?

**Comment by szha** [comment]
@cfRod thanks for the workaround!
