### PR TITLE
Fixes openblas static build

### LINKED ISSUE #16021: [CI] openblas build failed in static build
I notice the openblas 0.3.5 build failed in static build but the CI still passed.

```
../libopenblasp-r0.3.5.a(cblas_sgemm.o): In function `cblas_sgemm':
gemm.c:(.text+0x57f): undefined reference to `sgemm_kernel_direct_performant'
gemm.c:(.text+0x5d8): undefined reference to `sgemm_kernel_direct'
collect2: error: ld returned 1 exit status
make[1]: *** [xscblat3] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [tests] Error 2
++++ make --quiet -j 72 PREFIX=/work/mxnet/staticdeps install
make[1]: warning: -jN forced in submake: disabling jobserver mode.
Generating openblas_config.h in /work/mxnet/staticdeps/include
Generating f77blas.h in /work/mxnet/staticdeps/include
Generating cblas.h in /work/mxnet/staticdeps/include
Copying LAPACKE header files to /work/mxnet/staticdeps/include
Copying the static library to /work/mxnet/staticdeps/lib
Copying the shared library to /work/mxnet/staticdeps/lib
install: cannot stat 'libopenblasp-r0.3.5.so': No such file or directory
make[1]: *** [install] Error 1
make: *** [install] Error 2
```
For example:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-15983/3/pipeline/297

### PR DESCRIPTION
**Pull request by perdasilva**
## Description ##
Fixes #16021. The static build fails with openblas v0.3.5, this PR bumps it to v0.3.7, which seems to work. Also, fixes error checking in the openblas installation to ensure errors will make CI fail.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### CODE REVIEW

**Comment by TaoLv** [comment]
Openblas build failed but the CI task reported success.
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-16065/1/pipeline/285

```
++++ make --quiet -j 72 PREFIX=/work/mxnet/staticdeps install
make[1]: warning: -jN forced in submake: disabling jobserver mode.
Generating openblas_config.h in /work/mxnet/staticdeps/include
Generating f77blas.h in /work/mxnet/staticdeps/include
Generating cblas.h in /work/mxnet/staticdeps/include
Copying LAPACKE header files to /work/mxnet/staticdeps/include
Copying the static library to /work/mxnet/staticdeps/lib
Copying the shared library to /work/mxnet/staticdeps/lib
install: cannot stat 'libopenblasp-r0.3.7.so': No such file or directory
make[1]: *** [install] Error 1
make: *** [install] Error 2
```

**Comment by perdasilva** [comment]
Right, I forgot to add a build flag. Still unhappy it's failing and marking it as a success. Let me see what I can do...

**Comment by perdasilva** [comment]
@TaoLv ok, I've identified the problem. It should notify failures properly now. Let's see if it greens up with the new Fortran build flag. 

Thanks for being thorough - and sorry for the mix up

**Comment by perdasilva** [comment]
It seems the issue is we don't build a share library when building openblas, and this makes the `make install` command fail...which is why the +e was there in the first place....let me see if I can fix it

**Comment by perdasilva** [comment]
Ok, I've removed the drop in error checking from the script and build both shared and static openblas libraries. This makes it so the `make install` stop does not fail. Adding the error checking makes it so that if there are any errors, CI will be notified...

**Comment by perdasilva** [comment]
@TaoLv all green and all good now =D could you please review?

File: tools/dependencies/openblas.sh [hunk 1]
```diff
@@ -18,9 +18,8 @@
 # under the License.
 
 # This script builds the static library of openblas that can be used as dependency of mxnet.
-set +e # This script throws an error but otherwise works
```
Comment (marcoabreu) [inline tools/dependencies/openblas.sh]: Lol, best comment ever

**Comment by marcoabreu** [comment]
What's the point of the flags you are removing?

**Comment by szha** [comment]
It was for disabling the production of dynamic library. It was added to avoid accidentally linking to the dynamic library.

**Comment by perdasilva** [comment]
With FLAG, throws error, we need to add the at least *set +e*/*set -e* around make install. This will still fail to stop CI in case of other failures...if we leave the NO_SHARED flag *make install* fails...

If there's a concern about linking against the .so, I could add an rm after the *make install*....?

**Comment by perdasilva** [comment]
@marcoabreu @szha it would be great to get an acceptance here =)

**Comment by TaoLv** [comment]
@marcoabreu @szha Could you please review again? I need pick it to the mkldnn-v1.0 feature branch. Currently it blocks two PRs there: #16012, #16064 .

**Comment by pengzhao-intel** [comment]
It's a blocking issue for us to upgrade MKL-DNN. 
I prefer to merge the PR if there's no other concern.
@szha @TaoLv @marcoabreu
