### PR TITLE
Fix #11214 ccache compilation

### LINKED ISSUE #11214: Flaky Docker build due to ccache
Flaky build test: 
```
++ nproc

+ make -j72

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_main.c.d -g -O2 -Wall -W -Werror -c -o src/main.o src/main.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_args.c.d -g -O2 -Wall -W -Werror -c -o src/args.o src/args.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_ccache.c.d -g -O2 -Wall -W -Werror -c -o src/ccache.o src/ccache.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_cleanup.c.d -g -O2 -Wall -W -Werror -c -o src/cleanup.o src/cleanup.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_compopt.c.d -g -O2 -Wall -W -Werror -c -o src/compopt.o src/compopt.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_conf.c.d -g -O2 -Wall -W -Werror -c -o src/conf.o src/conf.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_counters.c.d -g -O2 -Wall -W -Werror -c -o src/counters.o src/counters.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_execute.c.d -g -O2 -Wall -W -Werror -c -o src/execute.o src/execute.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_exitfn.c.d -g -O2 -Wall -W -Werror -c -o src/exitfn.o src/exitfn.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_hash.c.d -g -O2 -Wall -W -Werror -c -o src/hash.o src/hash.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_hashutil.c.d -g -O2 -Wall -W -Werror -c -o src/hashutil.o src/hashutil.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_language.c.d -g -O2 -Wall -W -Werror -c -o src/language.o src/language.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_lockfile.c.d -g -O2 -Wall -W -Werror -c -o src/lockfile.o src/lockfile.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_manifest.c.d -g -O2 -Wall -W -Werror -c -o src/manifest.o src/manifest.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_mdfour.c.d -g -O2 -Wall -W -Werror -c -o src/mdfour.o src/mdfour.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_stats.c.d -g -O2 -Wall -W -Werror -c -o src/stats.o src/stats.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_unify.c.d -g -O2 -Wall -W -Werror -c -o src/unify.o src/unify.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_util.c.d -g -O2 -Wall -W -Werror -c -o src/util.o src/util.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_version.c.d -g -O2 -Wall -W -Werror -c -o src/version.o src/version.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_getopt_long.c.d -g -O2 -Wall -W -Werror -c -o src/getopt_long.o src/getopt_long.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_hashtable.c.d -g -O2 -Wall -W -Werror -c -o src/hashtable.o src/hashtable.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_hashtable_itr.c.d -g -O2 -Wall -W -Werror -c -o src/hashtable_itr.o src/hashtable_itr.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_murmurhashneutral2.c.d -g -O2 -Wall -W -Werror -c -o src/murmurhashneutral2.o src/murmurhashneutral2.c

gcc -DHAVE_CONFIG_H -DSYSCONFDIR=/usr/local/etc -I. -I./src -I./unittest  -MD -MP -MF .deps/src_snprintf.c.d -g -O2 -Wall -W -Werror -c -o src/snprintf.o src/snprintf.c

gcc -g -O2 -Wall -W -Werror -o ccache src/main.o src/args.o src/ccache.o src/cleanup.o src/compopt.o src/conf.o src/counters.o src/execute.o src/exitfn.o src/hash.o src/hashutil.o src/language.o src/lockfile.o src/manifest.o src/mdfour.o src/stats.o src/unify.o src/util.o src/version.o src/getopt_long.o src/hashtable.o src/hashtable_itr.o src/murmurhashneutral2.o src/snprintf.o   -lm  -lz

+ make install

asciidoc -a revnumber=3.4.2 -d manpage -b docbook -o - doc/MANUAL.adoc | \

  perl -pe 's!<literal>(.*?)</literal>!<emphasis role="strong">\1</emphasis>!g' >doc/MANUAL.xml

a2x --doctype manpage --format manpage doc/MANUAL.xml

a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/etc/asciidoc/docbook-xsl/manpage.xsl" "/work/deps/ccache/doc/MANUAL.xml" returned non-zero exit status 5

dev.mk:175: recipe for target 'doc/ccache.1' failed

make: *** [doc/ccache.1] Error 1

The command '/bin/sh -c /work/ubuntu_ccache.sh' returned a non-zero code: 2

Traceback (most recent call last):

  File "ci/build.py", line 347, in <module>

    sys.exit(main())

  File "ci/build.py", line 273, in main

    build_docker(platform, docker_binary, registry=args.docker_registry)

  File "ci/build.py", line 83, in build_docker

    check_call(cmd)

  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['docker', 'build', '-f', 'docker/Dockerfile.build.jetson', '--build-arg', 'USER_ID=1001', '--cache-from', 'mxnetci/build.jetson', '-t', 'mxnetci/build.jetson', 'docker']' returned non-zero exit status 2

script returned exit code 1

```
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11197/5/pipeline

### PR DESCRIPTION
**Pull request by larroy**
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)

### CODE REVIEW

File: ci/docker/install/ubuntu_ccache.sh [hunk 1]
```diff
@@ -24,6 +24,12 @@ set -ex
 pushd .
 
 apt update
+apt install -y \
```
Comment (lebeg) [inline ci/docker/install/ubuntu_ccache.sh]: You could just remove `--no-install-recommends` from the call below - it would install most of the necessary packages. Actually, we had quite a discussion about where this installs should go: https://github.com/apache/incubator-mxnet/pull/11096 I'm not sure what was the outcome of it.
