### PR TITLE
Fix nd.pick large array issue

### LINKED ISSUE #9314: nd.pick core dumps on large array
```
ubuntu@ip-172-31-13-31:~/mxnet$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
>>> a = mx.nd.ones((256*35, 1024*1024))
>>> b = mx.nd.ones((256*35,))
>>> mx.nd.pick(a,b)
Segmentation fault (core dumped)
```

Usually large array complains about shape mismatch, this one core dumps immediately.

### PR DESCRIPTION
**Pull request by ChaiBapchya**
## Description ##
large op support (using index_t and size_t instead of int) based off of #13418
Fixes #9314
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [pr-awaiting-review]

File: src/operator/tensor/broadcast_reduce_op.h [hunk 1]
```diff
@@ -1172,18 +1172,18 @@ void L2NormComputeEx(const nnvm::NodeAttrs& attrs,
 template<int ndim, bool clip = true>
 struct pick {
   template<typename DType, typename IType>
-  MSHADOW_XINLINE static void Map(int i, DType* out, const DType* a,
-                                  const IType *idx, int M, int stride,
+  MSHADOW_XINLINE static void Map(index_t i, DType* out, const DType* a,
+                                  const IType *idx, size_t M, int stride,
```
Comment (apeforest) [inline src/operator/tensor/broadcast_reduce_op.h]: Can we just use `index_t` for M so you don't need so many casting in this function?

Comment (yuxihu) [reply src/operator/tensor/broadcast_reduce_op.h]: +1 for using index_t for M.

Comment (ChaiBapchya) [reply src/operator/tensor/broadcast_reduce_op.h]: Sure. i looked at other places where large array support was mentioned. It seemed that
`index_t` was used where the variable is used as index
and `size_t` was used otherwise. Hence I stuck to that. But I'll change it to avoid casting if that's what's useful.

**Comment by eric-haibin-lin** [comment]
lgtm

File: tests/nightly/test_large_array.py [hunk 2]
```diff
@@ -145,6 +145,11 @@ def test_where():
     res = nd.sparse.where(csr_cond, a, b)
     assert np.sum(res[0].asnumpy() == 1) == b.shape[1]
 
+def test_pick():
```
Comment (apeforest) [inline tests/nightly/test_large_array.py]: This test is not sufficient. I ran it in current MXNet master and it passed as well.

Comment (eric-haibin-lin) [reply tests/nightly/test_large_array.py]: The new test fails on master. Looks good now
