### PR TITLE
Fix #17267, add expected and got datatype for concat error msgs

### LINKED ISSUE #17267: Unclear error message in np.dstack
## Description
`mxnet.np.dstack` throws dtype mismatch if one input is `int32` and the other is `float32`.  However, the error message is not that clear: 
```
mxnet.base.MXNetError: [18:18:56] /generic-flavor/src/src/operator/nn/concat.cc:152: Check failed: i == dtype || i == -1: Non-uniform data type in Concat
Stack trace:
  /lib/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x24) [0x7f776418f5a4]
  /lib/libmxnet.so(+0x3523b10) [0x7f77664b4b10]
  /lib/libmxnet.so(mxnet::imperative::SetShapeType(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, mxnet::DispatchMode*)+0x46d) [0x7f776600f8ed]
  /lib/libmxnet.so(mxnet::Imperative::Invoke(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&)+0x297) [0x7f7766005137]
  /lib/libmxnet.so(MXImperativeInvokeImpl(void*, int, void**, int*, void***, int, char const**, char const**)+0x5e5) [0x7f7765f11a05]
  /lib/libmxnet.so(MXImperativeInvokeEx+0x67) [0x7f7765f12d97]
  /python3.6/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f778ecbcef8]
  /python3.6/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call+0x15f) [0x7f778ecbbfff]
  /python3.6/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x292) [0x7f778ecb3e02]

```

When this op is use in a nested gluon block, it's a bit hard to investigate what are the actual types of input 0 and input 1. It will be much more helpful if the actual data types can be printed.

### PR DESCRIPTION
**Pull request by litaotju**
## Description ##
Fix #17267, add expected and got datatype for concat error msgs

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [ ] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at https://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [ ] To the best of my knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

File: src/operator/nn/concat.cc [hunk 1]
```diff
@@ -149,9 +149,10 @@ bool ConcatType(const nnvm::NodeAttrs& attrs,
     if (dtype == -1) {
       dtype = i;
     } else {
-      CHECK(i == dtype ||
-          i == -1) <<
-          "Non-uniform data type in Concat";
+      CHECK( i == dtype || i == -1)
```
Comment (eric-haibin-lin) [inline src/operator/nn/concat.cc]: Thanks for the fix! Two suggestions: 
- this function is used for both Concat and dstack. Can we extend the error msg to `Non-uniform data type in Concat / dstack.... ` ?
- can we extend the last sentenve and show the index of the data type : `..... got data type x at position y`?

Comment (litaotju) [reply src/operator/nn/concat.cc]: Do you want to split the msg explicitly of "Concat" and "dstack" based on the op name. Or just  use the sentence "Non-uniform data type in Concat / dstack....", and no need to state if it's Concat or dstack ? 

Yes, the second one can be done.

Comment (eric-haibin-lin) [reply src/operator/nn/concat.cc]: Split the msg sounds more clear. Maybe we can template the function with the op name

Comment (litaotju) [reply src/operator/nn/concat.cc]: Add the op info in msg. Marking as resolved. Feel free to re-open.

**Comment by haojin2** [comment]
@litaotju Please fix the lint problem: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fsanity/detail/PR-17271/2/pipeline.

**Comment by litaotju** [comment]
> @litaotju Please fix the lint problem: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fsanity/detail/PR-17271/2/pipeline.

Thanks @haojin2, fixed by https://github.com/apache/incubator-mxnet/pull/17271/commits/c835c36af6f43c245674362c6ccb2f51ab52e67d

**Comment by eric-haibin-lin** [comment]
Great. Thansk for the fix! @litaotju
