### PR TITLE
Disable test coverage of C++ codebase on CI 

### LINKED ISSUE #15971: CI fails with `PC-relative offset overflow in PLT entry`
Description

Clang build failed with:
```
lib/libmxnet.so: PC-relative offset overflow in PLT entry for `_ZN5mxnet2op8mxnet_op6KernelINS0_16ElemwiseBinaryOp15MissingLValueOpINS1_19backward_grad_tunedINS0_10mshadow_op8cos_gradEEELi3EEEN7mshadow3cpuEE11LaunchTunedIS8_dJPdSE_EEEvPNSA_6StreamISB_EEmDpT1_'
```

Full log:
```
/usr/bin/../lib/gcc/x86_64-linux-gnu/8.0.1/../../../x86_64-linux-gnu/crti.o: In function `_init':

(.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'

build/src/operator/numpy/random/np_uniform_op.o: In function `mxnet::op::NumpyUniformParam::__MANAGER__()':

np_uniform_op.cc:(.text+0x8): relocation truncated to fit: R_X86_64_PC32 against `.bss'

np_uniform_op.cc:(.text+0xf): relocation truncated to fit: R_X86_64_PC32 against `.bss'

np_uniform_op.cc:(.text+0x16): relocation truncated to fit: R_X86_64_PC32 against `.bss'

np_uniform_op.cc:(.text+0x2e): relocation truncated to fit: R_X86_64_PC32 against `.bss'

np_uniform_op.cc:(.text+0x36): relocation truncated to fit: R_X86_64_PC32 against `.bss'

np_uniform_op.cc:(.text+0x43): relocation truncated to fit: R_X86_64_PC32 against `.bss'

np_uniform_op.cc:(.text+0x5f): relocation truncated to fit: R_X86_64_PC32 against `.data'

np_uniform_op.cc:(.text+0x6b): relocation truncated to fit: R_X86_64_PC32 against `.bss'

np_uniform_op.cc:(.text+0x7b): relocation truncated to fit: R_X86_64_PC32 against `.bss'

np_uniform_op.cc:(.text+0x83): additional relocation overflows omitted from the output

/usr/bin/../lib/gcc/x86_64-linux-gnu/8.0.1/../../../x86_64-linux-gnu/crti.o: In function `_init':

(.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'

/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS): In function `__pthread_atfork':

/build/glibc-LK5gWL/glibc-2.23/nptl/pthread_atfork.c:54:(.text+0x3): relocation truncated to fit: R_X86_64_32S against symbol `__dso_handle' defined in .data section in /usr/bin/../lib/gcc/x86_64-linux-gnu/8.0.1/crtbegin.o

/usr/lib/x86_64-linux-gnu/libc_nonshared.a(atexit.oS): In function `atexit':

(.text+0x3): relocation truncated to fit: R_X86_64_32S against symbol `__dso_handle' defined in .data section in /usr/bin/../lib/gcc/x86_64-linux-gnu/8.0.1/crtbegin.o

/tmp/im2rec-31b2d6.o: In function `GetInterMethod(int, int, int, int, int, std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>&)':

im2rec.cc:(.text+0x9): relocation truncated to fit: R_X86_64_PC32 against `.bss'

im2rec.cc:(.text+0x11): relocation truncated to fit: R_X86_64_PC32 against `.bss'

im2rec.cc:(.text+0x58): relocation truncated to fit: R_X86_64_PC32 against `.bss'

im2rec.cc:(.text+0x65): relocation truncated to fit: R_X86_64_PC32 against `.bss'

im2rec.cc:(.text+0x89): relocation truncated to fit: R_X86_64_PC32 against `.bss'

im2rec.cc:(.text+0x92): relocation truncated to fit: R_X86_64_PC32 against `.bss'

im2rec.cc:(.text+0xa2): relocation truncated to fit: R_X86_64_PC32 against `.bss'

im2rec.cc:(.text+0xaa): additional relocation overflows omitted from the output

lib/libmxnet.so: PC-relative offset overflow in PLT entry for `_ZN5mxnet2op8mxnet_op6KernelINS0_16ElemwiseBinaryOp15MissingLValueOpINS1_19backward_grad_tunedINS0_10mshadow_op8cos_gradEEELi3EEEN7mshadow3cpuEE11LaunchTunedIS8_dJPdSE_EEEvPNSA_6StreamISB_EEmDpT1_'

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Makefile:580: recipe for target 'lib/libmxnet.so' failed

make: *** [lib/libmxnet.so] Error 1

make: *** Waiting for unfinished jobs....

bin/im2rec: PC-relative offset overflow in PLT entry for `vslDeleteStream'

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Check below log for details:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fclang/detail/PR-15970/1/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fclang/detail/PR-15961/5/pipeline

### PR DESCRIPTION
**Pull request by stu1130**
## Description ##
Related to #15971
### Root Cause
When linker link the object files, it uses relative addressing method. The error happens when the project is too large for linker to link the target objects using relative addressing with 32-bit address.
### Things we have tried
1. add -fPIC flag to make sure the shared library can be loaded at any address in memory. It end up with the same error message.
2. add -mcmodel=large. GCC default use -mcmodel=small where the program and symbols must be linked within 2 GB which is 32 bit address space. When it is set to large, there is no 2GB limitation. Unfortunately, all the code MXNet statically link including MKLDNN will need to build this way. It also ended up with same failure. So it leaded to our final solution.
3. Removing the test_coverage flag which injects monitoring code every if else branch, while loop, etc.It dramatically increase the size of libmxnet.a with test coverage. After removing the test coverage flag, it passed the Clang MKLDNN CI job.

After discussion with @marcoabreu, we agreed to disable C++ backend test coverage monitoring, which will also boost the CI.

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

## Comments ##
@marcoabreu could you help check if some runtime functions are missing or some functions should not disable? Thanks

### CODE REVIEW

**Comment by marcoabreu** [comment]
@anirudhacharya  I already approved

File: include/mxnet/tuple.h [hunk 1]
```diff
@@ -199,7 +199,11 @@ class Tuple {
...
   inline ValueType& operator[](int i) {
-    CHECK(i >= 0 && i < ndim()) << "index = " << i << " must be in range [0, " << ndim() << ")";
+    // it fixes the false alarm of assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
+    #pragma GCC diagnostic push
+    #pragma GCC diagnostic ignored "-Wstrict-overflow"
+      CHECK(i >= 0 && i < ndim()) << "index = " << i << " must be in range [0, " << ndim() << ")";
+    #pragma GCC diagnostic pop
     return begin()[i];
   }
   /*!
```
Comment (anirudh2290) [inline include/mxnet/tuple.h]: we can add for the below function too.

Comment (stu1130) [reply include/mxnet/tuple.h]: done
