### PR TITLE
gpu mem pool strategy

### LINKED ISSUE #10453: Bug of CuDNN RNN with variable sequence length
## Description
Segfault will be triggered by the following code:

```python
from mxnet.gluon.rnn import LSTM
import mxnet as mx
import numpy as np

ctx = mx.gpu()
lstm = LSTM(num_layers=1, hidden_size=200, dropout=0.5)
lstm.initialize(ctx=ctx)
batch_size = 32
for seq_len in range(500, 10, -1):
    for repeat in range(10):
        print(seq_len, repeat)
        inputs_nd = mx.nd.random.normal(0, 1, shape=(seq_len, batch_size, 200), ctx=ctx)
        out = lstm(inputs_nd)
        print(out[0].sum().asscalar())
        mx.nd.waitall()
```

I'm using V100 + cuda 9.0 + cudnn 7.0.4 (P3 instance).  The GPU memory keeps increasing and finally raises seg fault.

Also, the same script + configuration has not triggered an error in M60 (g3 instance).

@eric-haibin-lin @DickJC123 @szha @szhengac 

backtrace:
```
#0  __GI___libc_free (mem=0x7f0000000000) at malloc.c:2951
#1  0x00007fff7252e6f9 in cudnnDestroyFilterDescriptor () from /usr/local/cuda/lib64/libcudnn.so.7
#2  0x00007fff99c3683c in mxnet::op::CuDNNRNNOp<float>::~CuDNNRNNOp() () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#3  0x00007fff99c36bd9 in mxnet::op::CuDNNRNNOp<float>::~CuDNNRNNOp() () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#4  0x00007fff97d9bde5 in dmlc::any::TypeOnHeap<mxnet::op::OperatorState>::destroy(dmlc::any::Data*) () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#5  0x00007fff9579d8e1 in std::_Sp_counted_ptr_inplace<mxnet::OpStatePtr::OpState, std::allocator<mxnet::OpStatePtr::OpState>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#6  0x00007fff9551bed7 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#7  0x00007fff97def885 in mxnet::imperative::PushOperator(mxnet::OpStatePtr const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode)::{lambda(mxnet::RunContext, mxnet::engine::CallbackOnComplete)#2}::~CallbackOnComplete() () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#8  0x00007fff97deff08 in std::_Function_base::_Base_manager<mxnet::imperative::PushOperator(mxnet::OpStatePtr const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode)::{lambda(mxnet::RunContext)#3}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<mxnet::imperative::PushOperator(mxnet::OpStatePtr const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode)::{lambda(mxnet::RunContext)#3}> const&, std::_Manager_operation) () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#9  0x00007fff982233a6 in std::_Function_base::_Base_manager<mxnet::engine::ThreadedEngine::PushSync(std::function<void (mxnet::RunContext)>, mxnet::Context, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, mxnet::FnProperty, int, char const*)::{lambda(mxnet::RunContext, mxnet::engine::CallbackOnComplete)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<mxnet::engine::ThreadedEngine::PushSync(std::function<void (mxnet::RunContext)>, mxnet::Context, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, mxnet::FnProperty, int, char const*)::{lambda(mxnet::RunContext, mxnet::engine::CallbackOnComplete)#1}> const&, std::_Manager_operation) () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#10 0x00007fff98229cc4 in mxnet::engine::ThreadedEngine::OnComplete(mxnet::engine::ThreadedOpr*) () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#11 0x00007fff982245c6 in mxnet::engine::ThreadedEngine::OnCompleteStatic(mxnet::Engine*, void*) () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#12 0x00007fff9821e868 in mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*) ()
   from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#13 0x00007fff9823419b in void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&) () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#14 0x00007fff982343fe in std::_Function_handler<void (std::shared_ptr<dmlc::ManualEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#3}::operator()() const::{lambda(std::shared_ptr<dmlc::ManualEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<dmlc::ManualEvent>&&) ()
   from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#15 0x00007fff9822e2aa in std::thread::_Impl<std::_Bind_simple<std::function<void (std::shared_ptr<dmlc::ManualEvent>)> (std::shared_ptr<dmlc::ManualEvent>)> >::_M_run() () from /home/ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so
#16 0x00007fffee4a2c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x00007ffff7bc16ba in start_thread (arg=0x7fff3ed07700) at pthread_create.c:333
#18 0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

### PR DESCRIPTION
**Pull request by szha**
## Description ##
adjust GPU memory pool strategy

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] add knob for minimum memory pool chunk size
- [x] add option (`MXNET_GPU_MEM_POOL_TYPE="Round"`) for using nearest power of 2 size for better memory reuse

## Comments ##
- fixes #10453 when using MXNET_GPU_MEM_POOL_TYPE="Round". Before the change, memory size must be exact match to reuse the chunk in memory pool. For the workload in #10453, it required cudaMalloc for 55.45GB, whereas with the rounding the cudaMalloc call reduced to 1.32GB, during which the memory usage largely stayed the same. It also helped speed up workloads and improve stability with variations in size that cannot be hybridized yet.

### CODE REVIEW

File: src/storage/pooled_storage_manager.h [hunk 1]
```diff
@@ -71,7 +78,7 @@ class GPUPooledStorageManager final : public StorageManager {
  private:
   void DirectFreeNoLock(Storage::Handle handle) {
     cudaError_t err = cudaFree(handle.dptr);
-    size_t size = handle.size + NDEV;
```
Comment (piiswrong) [inline src/storage/pooled_storage_manager.h]: are you sure + NDEV is not needed any more? what if NDEV=32 and min_chunk=33 and handle.size=30? Original code would allocate 62. New code would allocate 33

File: src/storage/pooled_storage_manager.h [hunk 2]
```diff
@@ -52,6 +54,11 @@ class GPUPooledStorageManager final : public StorageManager {
    */
   GPUPooledStorageManager() {
     reserve_ = dmlc::GetEnv("MXNET_GPU_MEM_POOL_RESERVE", 5);
+    min_chunk_ = dmlc::GetEnv("MXNET_GPU_MEM_POOL_MIN_CHUNK", 4096);
```
Comment (piiswrong) [inline src/storage/pooled_storage_manager.h]: page size instead of min chunk?

File: src/storage/pooled_storage_manager.h [hunk 3]
```diff
@@ -82,19 +89,19 @@ class GPUPooledStorageManager final : public StorageManager {
  private:
   void ReleaseAll();
   // used memory
-  size_t used_memory_ = 0;
+  size_t used_memory_ = 0, min_chunk_;
```
Comment (piiswrong) [inline src/storage/pooled_storage_manager.h]: new line

File: src/storage/pooled_storage_manager.h [hunk 4]
```diff
@@ -129,13 +136,224 @@ void GPUPooledStorageManager::ReleaseAll() {
...
+  void DirectFree(Storage::Handle handle) override {
+    handle.size = get_size(get_bucket(handle.size));
+    std::lock_guard<std::mutex> lock(Storage::Get()->GetMutex(Context::kGPU));
+    DirectFreeNoLock(handle);
+  }
+
+ private:
+#if __SIZEOF_SIZE_T__ == __SIZEOF_LONG__
+
+#if defined(__clang__) || defined(__GNUC__)
```
Comment (piiswrong) [inline src/storage/pooled_storage_manager.h]: does this need to be so complicated? You just need to take the highest bit and shift left by 1 if it's smaller than size.

This is called the finding the MSB. See https://www.google.com/search?ei=__UNW-DMG6iF0wLqyr4g&q=how+to+find+most+significant+bit+in+c&oq=take+highest+bit&gs_l=psy-ab.1.0.0i71k1l8.0.0.0.4417.0.0.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..0.0.0....0.LUbIFjlZyeU

File: src/storage/pooled_storage_manager.h (hunk 1 above)
Comment (szha) [reply src/storage/pooled_storage_manager.h]: cc'd @ptrendx. My understanding on this was that there needs to be enough bytes to make sure that for 32 devices at least each device has 1 byte, for nccl scattering. Could you confirm, @ptrendx?

Comment (ptrendx) [reply src/storage/pooled_storage_manager.h]: Yes, that is correct.

File: src/storage/pooled_storage_manager.h (hunk 4 above)
Comment (szha) [reply src/storage/pooled_storage_manager.h]: these builtins would utilize hardware instructions when available.

Comment (piiswrong) [reply src/storage/pooled_storage_manager.h]: Is it really faster? It looks too complicated.

Comment (piiswrong) [reply src/storage/pooled_storage_manager.h]: also the default implementation with pow and log is really slow

Comment (szha) [reply src/storage/pooled_storage_manager.h]: I will change the default implementation to use bit shifting and then do a comparison

Comment (szha) [reply src/storage/pooled_storage_manager.h]: I compared my current solution, the bit shifting, and `static_cast<int>(std::ceil(std::log2(s)))`, with `-O3` is turned on on my mac (clang), the speed looks like the following:
```
Running 10000000 iters.
Addr width 64
It took me 0.00981569 seconds. result: 223222785
It took me 0.128623 seconds. result: 223222785
It took me 0.0801588 seconds. result: 223222785
```

**Comment by szha** [comment]
I've simplified the implementation to exclude optimization using intrinsics and bit scans. They are backed up in https://github.com/szha/mxnet/tree/mem_strategy_backup

File: amalgamation/amalgamation.py [hunk 5]
```diff
@@ -23,7 +23,7 @@
 import platform
 
 blacklist = [
-    'Windows.h', 'cublas_v2.h', 'cuda/tensor_gpu-inl.cuh',
+    'Windows.h', 'intrin.h', 'cublas_v2.h', 'cuda/tensor_gpu-inl.cuh',
```
Comment (piiswrong) [inline amalgamation/amalgamation.py]: revert

File: tests/cpp/storage/storage_test.cc [hunk 6]
```diff
@@ -60,5 +61,39 @@ TEST(Storage, Basic_GPU) {
     storage->Free(handle);
   }
 }
+
+TEST(GPUStorage, Round_GPU) {
+  if (mxnet::test::unitTestsWithCuda) {
+    putenv("MXNET_GPU_MEM_POOL_ROUND_LINEAR_CUTOFF=20");
```
Comment (marcoabreu) [inline tests/cpp/storage/storage_test.cc]: How long does this variable persist? It could have side effects on other tests

File: tests/cpp/storage/storage_test.cc [hunk 7]
```diff
@@ -22,11 +21,13 @@
  * \file storage_test.cc
  * \brief cpu/gpu storage tests
 */
+#include <stdlib.h>
 #include <gtest/gtest.h>
 #include <dmlc/logging.h>
 #include <mxnet/storage.h>
 #include <cstdio>
 #include "test_util.h"
+#include "storage/pooled_storage_manager.h"
```
Comment (marcoabreu) [inline tests/cpp/storage/storage_test.cc]: Duplicate import? I think it's already part of the storage namespave

File: tests/python/unittest/test_sparse_operator.py [hunk 8]
```diff
@@ -16,7 +16,7 @@
 # under the License.
 
 from mxnet.test_utils import *
-from common import setup_module, with_seed
+from common import setup_module, with_seed, teardown
```
[the remark this answers is not in the document]
Comment (szha) [reply tests/python/unittest/test_sparse_operator.py]: applying this change would allow all tests within a module to finish before moving onto the next test, thus eliminating the case where side effect of tests in another module spills over to the next. In terms of testing practice, including a setup/teardown is common.

[the remark this answers is not in the document]
Comment (marcoabreu) [reply tests/python/unittest/test_sparse_operator.py]: Yeah, but we're not actually using it in most files, right?

[the remark this answers is not in the document]
Comment (szha) [reply tests/python/unittest/test_sparse_operator.py]: now we are

[the remark this answers is not in the document]
Comment (marcoabreu) [reply tests/python/unittest/test_sparse_operator.py]: Ah in common.py :) But isn't it sufficient to import it there?

[the remark this answers is not in the document]
Comment (szha) [reply tests/python/unittest/test_sparse_operator.py]: unfortunately no. it is the same case as setup_module

[the remark this answers is not in the document]
Comment (marcoabreu) [reply tests/python/unittest/test_sparse_operator.py]: argh :/

File: src/storage/pooled_storage_manager.h [hunk 9]
```diff
@@ -129,13 +139,172 @@ void GPUPooledStorageManager::ReleaseAll() {
...
+void GPUPooledRoundedStorageManager::Alloc(Storage::Handle* handle) {
+  std::lock_guard<std::mutex> lock(Storage::Get()->GetMutex(Context::kGPU));
+  int bucket = get_bucket(handle->size);
+  size_t size = get_size(bucket);
+  auto&& reuse_pool = memory_pool_[bucket];
+  if (reuse_pool.size() == 0) {
+    size_t free, total;
+    cudaMemGetInfo(&free, &total);
+    if (free <= total * reserve_ / 100 || size > free - total * reserve_ / 100)
+      ReleaseAll();
```
Comment (lebeg) [inline src/storage/pooled_storage_manager.h]: What will happen to the storage handles currently pointing to some of the memory?

File: src/storage/pooled_storage_manager.h [hunk 10]
```diff
@@ -129,13 +139,172 @@ void GPUPooledStorageManager::ReleaseAll() {
...
+  // memory pool
+  std::vector<std::vector<void*>> memory_pool_;
+  DISALLOW_COPY_AND_ASSIGN(GPUPooledRoundedStorageManager);
+};  // class GPUPooledRoundedStorageManager
+
+void GPUPooledRoundedStorageManager::Alloc(Storage::Handle* handle) {
+  std::lock_guard<std::mutex> lock(Storage::Get()->GetMutex(Context::kGPU));
+  int bucket = get_bucket(handle->size);
+  size_t size = get_size(bucket);
+  auto&& reuse_pool = memory_pool_[bucket];
```
Comment (lebeg) [inline src/storage/pooled_storage_manager.h]: Even if it's no error (the rvalue reference will de deduced to normal lvalue reference) it's better to use it explicitly as auto&

**Comment by ThomasDelteil** [comment]
@szha should we document this new env variable or is it still experimental?

**Comment by szha** [comment]
@ThomasDelteil I intended to have people experiment with this first.
