### PR TITLE
[BUGFIX]Fix cuDNN dropout reproducibility

### LINKED ISSUE #15662: cudnn Dropout reproducibility
https://github.com/apache/incubator-mxnet/blob/master/src/operator/nn/dropout-inl.h#L491-L493

The seed of CUDNN dropout does not respect the random seed in mxnet

### PR DESCRIPTION
**Pull request by ptrendx**
## Description ##
Fixes #15662

This PR seeds the dropout states inside the `ResourceManager` when `mx.random.seed` method is called and makes Dropout and RNN ops reuse those states in their dropout descriptors.

@szha @eric-haibin-lin @DickJC123 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### CODE REVIEW

File: src/resource.cc [hunk 1]
```diff
@@ -428,37 +486,28 @@ void* Resource::get_host_space_internal(size_t size) const {
...
+    CHECK(state_space->handle.size > 0)
+      << "CUDNN dropout descriptor was not initialized yet!";
     // cudnnRestoreDropoutDescriptor() introduced with cuDNN v7
     STATIC_ASSERT_CUDNN_VERSION_GE(7000);
     CUDNN_CALL(cudnnRestoreDropoutDescriptor(*dropout_desc, stream->dnn_handle_,
                                              dropout,
                                              state_space->handle.dptr,
                                              state_space->handle.size,
-                                             seed));
+                                             0));
```
Comment (szha) [inline src/resource.cc:510]: does the seed not matter?

File: tests/python/gpu/test_gluon_gpu.py [hunk 2]
```diff
@@ -647,3 +647,31 @@ def test_gemms_true_fp16():
     assert_almost_equal(ref_results.asnumpy(), results_trueFP16.asnumpy(),
                         atol=atol, rtol=rtol)
 
+@with_seed()
+def test_cudnn_dropout_reproducibility():
```
Comment (szha) [inline tests/python/gpu/test_gluon_gpu.py:651]: @assert_raises_cudnn_not_satisfied?

File: src/resource.cc (hunk 1 above)
Comment (ptrendx) [reply src/resource.cc:510]: It does not matter. From cuDNN API reference:
```
seed
Input. Seed used in prior call to cudnnSetDropoutDescriptor() that initialized states buffer. Using a different seed from this has no effect. A change of seed, and subsequent update to random number generator states can be achieved by calling cudnnSetDropoutDescriptor().
```

File: tests/python/gpu/test_gluon_gpu.py (hunk 2 above)
Comment (ptrendx) [reply tests/python/gpu/test_gluon_gpu.py:652]: :+1:

**Review by szha — APPROVED** [review]
thanks for fixing the long standing issue!

**Comment by ptrendx** [comment]
@szha Over the course of testing this PR I discovered a different possibility of the nondeterminism - if there are more than 1 copies of the dropout resource (or random resource for that matter) then you end up with the race condition of getting a new resource and call to `seed` setting the counter to 0. We could either remove the copies > 1 (and also remove parallelrandom resource, which has the same problem), or adding `waitall` to the `seed` call. Which one do you think is a better solution?

File: tests/python/gpu/test_gluon_gpu.py (hunk 2 above)
Comment (ptrendx) [reply tests/python/gpu/test_gluon_gpu.py:652]: Ok, so this does not really work since the test does not really throw when cudnn is not supported. I will revert that.

**Comment by szha** [comment]
That's a good point. It's unclear to me what the performance impact would be if we don't allow multiple copies of random states in case one doesn't care about reproducibility. Also, I'm not sure whether waitall resolves the race condition completely in the case where multi-threaded execution happens and we use the thread-safe cached op.

**Comment by ptrendx** [comment]
Actually it seems the `waitall` when seeding does not really help, while having only a single copy works well every time. Let me dig deeper into this.

**Comment by ptrendx** [comment]
Ok, I understand now the problem with reproducibility I saw - `cudnnSetDropoutDescriptor` is asynchronous and there was no proper synchronization of the CUDA stream, so if `cudnnSetDropoutDescriptor` was picked up by 1 thread and the dropout was picked up by another thread, there was race condition on the CUDA side. I fixed that in the latest commit.

I still believe that there is a potential problem for resource assignment, although that is not something that would be typically hit as the ops are launched typically from a single thread. The thread-safe cachedop would be the main reason for this to fail, although it would require somebody to seed frequently during the execution, so that is also not very common scenario.

File: tests/python/gpu/test_gluon_gpu.py (hunk 2 above)
Comment (szha) [reply tests/python/gpu/test_gluon_gpu.py:651]: you can use runtime feature detection to determine whether to skip the test.

**Review by DickJC123 — APPROVED** [review]
Thanks for adding the testing.  As you explained on a side channel, there is no need for a mx.nd.waitall in the tests or normal usage, as this PR takes care of synchronizing mx.random.seed() calls by the Python thread and use of Dropout resources by the backend Engines.

I'm particularly happy to see the removal of the cpu rand() call.  This PR is a great step toward achieving determinism.   LGTM.
