### PR TITLE
enabling test_dropout after fixing flaky issue

### LINKED ISSUE #12314: flaky test: test_operator.test_dropout
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12311/1/pipeline
```
======================================================================

FAIL: test_operator.test_dropout

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 5844, in test_dropout

    check_dropout_ratio(0.0, shape)

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 5788, in check_dropout_ratio

    assert exe.outputs[0].asnumpy().min() == min_value

AssertionError: 

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=119185068 to reproduce.

--------------------- >> end captured logging << ---------------------
```

### PR DESCRIPTION
**Pull request by mseth10**
## Description ##
Enabled unit test for dropout. Fixed flaky behavior on MKLDNN CPU. Fixes #12314 .

### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [MXNET-$JIRA_ID], where $JIRA_ID refers to the relevant [JIRA issue](https://issues.apache.org/jira/projects/MXNET/issues) created (except PRs with tiny changes)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage:
- Unit tests are added for small changes to verify correctness (e.g. adding a new operator)
- Nightly tests are added for complicated/long-running ones (e.g. changing distributed kvstore)
- Build tests will be added for build configuration changes (e.g. adding a new build option with NCCL)
- [x] Code is well-documented: 
- For user-facing API changes, API doc string has been updated. 
- For new C++ functions in header files, their functionalities and arguments are documented. 
- For new examples, README.md is added to explain the what the example does, the source of the dataset, expected performance on test set and reference to the original paper if applicable
- Check the API doc at http://mxnet-ci-doc.s3-accelerate.dualstack.amazonaws.com/PR-$PR_ID/$BUILD_ID/index.html
- [x] To the my best knowledge, examples are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] BernoulliGenerate function modified to pass constant positive seed to vslNewStream function of MKL across different threads.

## Comments ##
- Found this error while going through another code stub using vslNewStream function https://github.com/intel/mklnn/blob/master/src/Random.c#L32

### CODE REVIEW

File: src/operator/nn/dropout-inl.h [hunk 1]
```diff
@@ -82,7 +82,7 @@ class DropoutOp {
   static void BernoulliGenerate(common::random::RandGenerator<cpu, DType> gen,
                                 int n, double p, int* r) {
     typename RandGenerator<xpu, DType>::Impl genImpl(&gen, 1);
-    const int seed = 17 + genImpl.rand() % 4096;  // NOLINT(runtime/threadsafe_fn)
+    const int seed = 17 + abs(genImpl.rand() % 4096);
     const int nthr = engine::OpenMP::Get()->GetRecommendedOMPThreadCount();
 #pragma omp parallel num_threads(nthr)
```
Comment (pengzhao-intel) [inline src/operator/nn/dropout-inl.h]: I think it will be better to change this parallel approach to "#pragma omp paralle for" so it will be more readable than OMP section parallel.
Do you mind to change it?

**Comment by pengzhao-intel** [comment]
@mseth10 Thanks for the fix :)

>  In the present code, different seed is passed to vslNewStream for different threads. Making the seeds constant fixes the flaky issue

Could you elaborate how do you make the seeds constant?

File: src/operator/nn/dropout-inl.h [hunk 2]
```diff
@@ -92,7 +92,7 @@ class DropoutOp {
       const int my_amount = std::min(my_offset + avg_amount, n) - my_offset;
       if (my_amount > 0) {
         VSLStreamStatePtr stream;
-        vslNewStream(&stream, VSL_BRNG_MCG31, seed + my_offset);
+        vslNewStream(&stream, VSL_BRNG_MCG31, seed);
```
Comment (mseth10) [inline src/operator/nn/dropout-inl.h]: @pengzhao-intel vslNewStream was passed (seed + my_offset) which is variable for different threads as my_offset depends on thread number. I have removed my_offset, so whatever seed value is generated, it's used to generate stream for each thread.

File: src/operator/nn/dropout-inl.h (hunk 1 above)
Comment (mseth10) [reply src/operator/nn/dropout-inl.h]: @pengzhao-intel Thanks for your feedback. I don't see why "#pragma omp parallel for" would be more readable in this case as there is no for loop involved. The job for each thread is defined based on its thread number. Introducing a for loop with "#pragma omp parallel for" would be redundant. Please correct me if I've misunderstood it.

Comment (mseth10) [reply src/operator/nn/dropout-inl.h]: @apeforest vslNewStream expects a non-negative integer as seed by definition. genImpl.rand() generates negative numbers too, which sometimes leads to negative seed values being passed to vslNewStream. abs() helps keep that in check.

File: src/operator/nn/dropout-inl.h (hunk 2 above)
Comment (mseth10) [reply src/operator/nn/dropout-inl.h]: @apeforest By removing my_offset from vslNewStream and making the seed same for all threads, we are ensuring that the same stream is generated for each thread.
For each thread, my_offset acts an index for vslSkipAheadStream and viRngBernoulli. It tells vslSkipAheadStream which section of stream to use and viRngBernoulli which section of vector to populate.

File: src/operator/nn/dropout-inl.h (hunk 1 above)
Comment (apeforest) [reply src/operator/nn/dropout-inl.h]: Thanks for the explanation. In this case I would suggest we add an assert here to make sure seed is nonnegative

**Comment by kalyc** [comment]
Hi @mseth10 thanks for your contribution!
Could you please add "Fixes <issue #>" in the PR description - so when this PR is closed, the issue will be closed automatically?

**Comment by kalyc** [comment]
@mxnet-label-bot add [pr-awaiting-review]

**Comment by apeforest** [comment]
Please also add your name to CONTRIBUTORS.md if you have not already done so.

File: src/operator/nn/dropout-inl.h (hunk 1 above)
Comment (mseth10) [reply src/operator/nn/dropout-inl.h]: Added a check to make sure seed is non-negative.

**Comment by pengzhao-intel** [comment]
@mseth10 thanks for the nice explanation in this PR.  Great work!
